import 'dotenv/config'
import { createClient } from '@libsql/client'

const client = createClient({
  url: process.env.TURSO_DATABASE_URL!,
  authToken: process.env.TURSO_AUTH_TOKEN!,
})

const categories = [
  { id: 'cat-1', name: 'Article & Blog Writing', slug: 'article-blog-writing', icon: 'FileText', description: 'Create compelling blog posts, articles, and content', sortOrder: 1 },
  { id: 'cat-2', name: 'Ads & Marketing', slug: 'ads-marketing', icon: 'Megaphone', description: 'Generate high-converting ad copy and marketing content', sortOrder: 2 },
  { id: 'cat-3', name: 'Social Media', slug: 'social-media', icon: 'Share2', description: 'Create engaging social media content for all platforms', sortOrder: 3 },
  { id: 'cat-4', name: 'Email', slug: 'email', icon: 'Mail', description: 'Craft professional emails that get results', sortOrder: 4 },
  { id: 'cat-5', name: 'Website & SEO', slug: 'website-seo', icon: 'Globe', description: 'Optimize your website content for search engines', sortOrder: 5 },
  { id: 'cat-6', name: 'E-Commerce', slug: 'e-commerce', icon: 'ShoppingCart', description: 'Write product descriptions and e-commerce content', sortOrder: 6 },
  { id: 'cat-7', name: 'Creative Writing', slug: 'creative-writing', icon: 'Sparkles', description: 'Unleash your creativity with stories, lyrics, and more', sortOrder: 7 },
  { id: 'cat-8', name: 'Business', slug: 'business', icon: 'Briefcase', description: 'Generate business documents and professional content', sortOrder: 8 },
  { id: 'cat-9', name: 'Code & Development', slug: 'code-development', icon: 'Code2', description: 'Generate code snippets and development documentation', sortOrder: 9 },
  { id: 'cat-10', name: 'Academic', slug: 'academic', icon: 'GraduationCap', description: 'Academic writing, grammar checking, and research tools', sortOrder: 10 },
  { id: 'cat-11', name: 'Video & Audio', slug: 'video-audio', icon: 'Video', description: 'Create video scripts, descriptions, and audio content', sortOrder: 11 },
  { id: 'cat-12', name: 'Other Tools', slug: 'other-tools', icon: 'Wrench', description: 'Miscellaneous AI-powered writing tools', sortOrder: 12 },
]

const toneOpts = JSON.stringify(['Professional','Casual','Formal','Friendly','Persuasive','Informative','Creative','Humorous'])
const langOpts = JSON.stringify(['English','Spanish','French','German','Portuguese','Italian','Dutch','Chinese','Japanese','Korean','Arabic','Hindi'])

const templates = [
  { id: 't-1', name: 'Blog Titles', slug: 'blog-titles', description: 'Generate catchy and SEO-friendly blog titles', icon: 'Heading', categoryId: 'cat-1', prompt: 'Generate {count} catchy blog titles about: {topic}. Audience: {audience}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'topic',label:'Blog Topic',type:'text',required:true},{name:'audience',label:'Target Audience',type:'text',required:false},{name:'count',label:'Number of Titles',type:'number',required:false}]), isPremium: 0, isFeatured: 1, sortOrder: 1 },
  { id: 't-2', name: 'Blog Section', slug: 'blog-section', description: 'Write a detailed blog section', icon: 'FileText', categoryId: 'cat-1', prompt: 'Write a blog section about: {section_topic}. Part of: {main_topic}. Words: {word_count}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'section_topic',label:'Section Topic',type:'text',required:true},{name:'main_topic',label:'Overall Topic',type:'text',required:true},{name:'word_count',label:'Word Count',type:'number',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 2 },
  { id: 't-3', name: 'Blog Ideas', slug: 'blog-ideas', description: 'Get creative blog post ideas', icon: 'Lightbulb', categoryId: 'cat-1', prompt: 'Generate {count} blog ideas for niche: {niche}. Audience: {audience}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'niche',label:'Blog Niche',type:'text',required:true},{name:'audience',label:'Audience',type:'text',required:false},{name:'count',label:'Number of Ideas',type:'number',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 3 },
  { id: 't-4', name: 'Article Generator', slug: 'article-generator', description: 'Generate complete articles on any topic', icon: 'Newspaper', categoryId: 'cat-1', prompt: 'Write a comprehensive article about: {topic}. Words: {word_count}. Audience: {audience}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'topic',label:'Article Topic',type:'text',required:true},{name:'audience',label:'Audience',type:'text',required:false},{name:'word_count',label:'Word Count',type:'number',required:false}]), isPremium: 1, isFeatured: 1, sortOrder: 4 },
  { id: 't-5', name: 'Content Rewriter', slug: 'content-rewriter', description: 'Rewrite content to make it fresh and unique', icon: 'RefreshCw', categoryId: 'cat-1', prompt: 'Rewrite this content while keeping the meaning: {content}. Goal: {rewrite_goal}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'content',label:'Content to Rewrite',type:'textarea',required:true},{name:'rewrite_goal',label:'Goal',type:'text',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 5 },
  { id: 't-6', name: 'Summarize Text', slug: 'summarize-text', description: 'Condense long text into clear summaries', icon: 'FileMinus', categoryId: 'cat-1', prompt: 'Summarize in {word_count} words: {content}. Style: {summary_style}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'content',label:'Text to Summarize',type:'textarea',required:true},{name:'word_count',label:'Summary Length',type:'number',required:false},{name:'summary_style',label:'Style',type:'text',required:false}]), isPremium: 0, isFeatured: 1, sortOrder: 6 },
  { id: 't-7', name: 'Facebook Ads', slug: 'facebook-ads', description: 'Create compelling Facebook ad copy', icon: 'Facebook', categoryId: 'cat-2', prompt: 'Create {count} Facebook ads for: {product_service}. Audience: {audience}. USP: {usp}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'product_service',label:'Product/Service',type:'text',required:true},{name:'audience',label:'Audience',type:'text',required:true},{name:'usp',label:'USP',type:'text',required:true},{name:'count',label:'Variations',type:'number',required:false}]), isPremium: 0, isFeatured: 1, sortOrder: 7 },
  { id: 't-8', name: 'Google Ads Headlines', slug: 'google-ads-headlines', description: 'Generate Google Ads headlines', icon: 'Search', categoryId: 'cat-2', prompt: 'Generate {count} Google Ads headlines for: {product_service}. Keywords: {keywords}. USP: {usp}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'product_service',label:'Product/Service',type:'text',required:true},{name:'keywords',label:'Keywords',type:'text',required:true},{name:'usp',label:'USP',type:'text',required:false},{name:'count',label:'Count',type:'number',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 8 },
  { id: 't-9', name: 'AIDA Framework', slug: 'aida-framework', description: 'Create copy using AIDA framework', icon: 'Target', categoryId: 'cat-2', prompt: 'Write AIDA copy for: {product_service}. Audience: {audience}. Benefit: {key_benefit}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'product_service',label:'Product/Service',type:'text',required:true},{name:'audience',label:'Audience',type:'text',required:true},{name:'key_benefit',label:'Key Benefit',type:'text',required:true}]), isPremium: 0, isFeatured: 1, sortOrder: 9 },
  { id: 't-10', name: 'Ad Headlines', slug: 'ad-headlines', description: 'General ad headline generator', icon: 'BadgeHeading', categoryId: 'cat-2', prompt: 'Generate {count} ad headlines for: {product_service}. Value prop: {value_prop}. Audience: {audience}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'product_service',label:'Product/Service',type:'text',required:true},{name:'value_prop',label:'Value Proposition',type:'text',required:true},{name:'audience',label:'Audience',type:'text',required:false},{name:'count',label:'Count',type:'number',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 10 },
  { id: 't-11', name: 'Instagram Captions', slug: 'instagram-captions', description: 'Generate engaging Instagram captions', icon: 'Camera', categoryId: 'cat-3', prompt: 'Write {count} Instagram captions about: {topic}. Post type: {post_type}. Include {hashtag_count} hashtags. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'topic',label:'Post Topic',type:'text',required:true},{name:'post_type',label:'Post Type',type:'text',required:false},{name:'count',label:'Captions',type:'number',required:false},{name:'hashtag_count',label:'Hashtags',type:'number',required:false}]), isPremium: 0, isFeatured: 1, sortOrder: 11 },
  { id: 't-12', name: 'Twitter Tweets', slug: 'twitter-tweets', description: 'Create engaging tweets', icon: 'Twitter', categoryId: 'cat-3', prompt: 'Write {count} tweets about: {topic}. Style: {style}. Include hashtags. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'topic',label:'Topic',type:'text',required:true},{name:'style',label:'Style',type:'text',required:false},{name:'count',label:'Count',type:'number',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 12 },
  { id: 't-13', name: 'LinkedIn Posts', slug: 'linkedin-posts', description: 'Create professional LinkedIn posts', icon: 'Linkedin', categoryId: 'cat-3', prompt: 'Write a LinkedIn post about: {topic}. Key message: {key_message}. CTA: {cta}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'topic',label:'Topic',type:'text',required:true},{name:'key_message',label:'Key Message',type:'text',required:true},{name:'cta',label:'Call to Action',type:'text',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 13 },
  { id: 't-14', name: 'Welcome Email', slug: 'welcome-email', description: 'Write welcome emails for new subscribers', icon: 'Mail', categoryId: 'cat-4', prompt: 'Write a welcome email for: {brand_name}. Product: {product}. Key benefit: {benefit}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'brand_name',label:'Brand Name',type:'text',required:true},{name:'product',label:'Product/Service',type:'text',required:true},{name:'benefit',label:'Key Benefit',type:'text',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 14 },
  { id: 't-15', name: 'Cold Email', slug: 'cold-email', description: 'Write effective cold outreach emails', icon: 'Mail', categoryId: 'cat-4', prompt: 'Write a cold email to: {recipient_role}. Offering: {product_service}. Value prop: {value_prop}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'recipient_role',label:'Recipient Role',type:'text',required:true},{name:'product_service',label:'Product/Service',type:'text',required:true},{name:'value_prop',label:'Value Proposition',type:'text',required:true}]), isPremium: 0, isFeatured: 1, sortOrder: 15 },
  { id: 't-16', name: 'Email Subject Lines', slug: 'email-subject-lines', description: 'Generate high-open-rate subject lines', icon: 'Mail', categoryId: 'cat-4', prompt: 'Generate {count} email subject lines for: {email_topic}. Goal: {goal}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'email_topic',label:'Email Topic',type:'text',required:true},{name:'goal',label:'Goal',type:'text',required:false},{name:'count',label:'Count',type:'number',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 16 },
  { id: 't-17', name: 'Meta Description', slug: 'meta-description', description: 'Write SEO meta descriptions', icon: 'Globe', categoryId: 'cat-5', prompt: 'Write a meta description for page: {page_title}. Topic: {topic}. Keywords: {keywords}. Max 160 chars. Language: {language}.', fields: JSON.stringify([{name:'page_title',label:'Page Title',type:'text',required:true},{name:'topic',label:'Topic',type:'text',required:true},{name:'keywords',label:'Keywords',type:'text',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 17 },
  { id: 't-18', name: 'FAQs', slug: 'faqs', description: 'Generate FAQ sections for websites', icon: 'HelpCircle', categoryId: 'cat-5', prompt: 'Generate {count} FAQs about: {topic}. Audience: {audience}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'topic',label:'Topic',type:'text',required:true},{name:'audience',label:'Audience',type:'text',required:false},{name:'count',label:'Number of FAQs',type:'number',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 18 },
  { id: 't-19', name: 'Product Description', slug: 'product-description', description: 'Write compelling product descriptions', icon: 'ShoppingBag', categoryId: 'cat-6', prompt: 'Write a product description for: {product_name}. Features: {features}. Benefits: {benefits}. Audience: {audience}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'product_name',label:'Product Name',type:'text',required:true},{name:'features',label:'Features',type:'textarea',required:true},{name:'benefits',label:'Benefits',type:'text',required:false},{name:'audience',label:'Audience',type:'text',required:false}]), isPremium: 0, isFeatured: 1, sortOrder: 19 },
  { id: 't-20', name: 'Product Name Generator', slug: 'product-name-generator', description: 'Generate creative product names', icon: 'Tag', categoryId: 'cat-6', prompt: 'Generate {count} product names for: {product_type}. Industry: {industry}. Style: {style}. Language: {language}.', fields: JSON.stringify([{name:'product_type',label:'Product Type',type:'text',required:true},{name:'industry',label:'Industry',type:'text',required:false},{name:'style',label:'Name Style',type:'text',required:false},{name:'count',label:'Count',type:'number',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 20 },
  { id: 't-21', name: 'Creative Stories', slug: 'creative-stories', description: 'Generate creative short stories', icon: 'BookOpen', categoryId: 'cat-7', prompt: 'Write a short story about: {topic}. Genre: {genre}. Length: {word_count} words. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'topic',label:'Story Topic',type:'text',required:true},{name:'genre',label:'Genre',type:'text',required:false},{name:'word_count',label:'Word Count',type:'number',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 21 },
  { id: 't-22', name: 'Song Lyrics', slug: 'song-lyrics', description: 'Write song lyrics in any genre', icon: 'Music', categoryId: 'cat-7', prompt: 'Write song lyrics about: {topic}. Genre: {genre}. Mood: {mood}. Language: {language}.', fields: JSON.stringify([{name:'topic',label:'Topic',type:'text',required:true},{name:'genre',label:'Genre',type:'text',required:false},{name:'mood',label:'Mood',type:'text',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 22 },
  { id: 't-23', name: 'Business Ideas', slug: 'business-ideas', description: 'Generate innovative business ideas', icon: 'Lightbulb', categoryId: 'cat-8', prompt: 'Generate {count} business ideas for: {industry}. Budget: {budget}. Skills: {skills}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'industry',label:'Industry',type:'text',required:true},{name:'budget',label:'Budget Range',type:'text',required:false},{name:'skills',label:'Your Skills',type:'text',required:false},{name:'count',label:'Count',type:'number',required:false}]), isPremium: 0, isFeatured: 1, sortOrder: 23 },
  { id: 't-24', name: 'Company Bio', slug: 'company-bio', description: 'Write professional company bios', icon: 'Building2', categoryId: 'cat-8', prompt: 'Write a company bio for: {company_name}. Industry: {industry}. Mission: {mission}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'company_name',label:'Company Name',type:'text',required:true},{name:'industry',label:'Industry',type:'text',required:true},{name:'mission',label:'Mission',type:'text',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 24 },
  { id: 't-25', name: 'Press Release', slug: 'press-release', description: 'Write professional press releases', icon: 'Newspaper', categoryId: 'cat-8', prompt: 'Write a press release for: {company_name}. Announcement: {announcement}. Details: {details}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'company_name',label:'Company',type:'text',required:true},{name:'announcement',label:'Announcement',type:'text',required:true},{name:'details',label:'Details',type:'textarea',required:false}]), isPremium: 1, isFeatured: 0, sortOrder: 25 },
  { id: 't-26', name: 'Academic Essay', slug: 'academic-essay', description: 'Write structured academic essays', icon: 'GraduationCap', categoryId: 'cat-10', prompt: 'Write an academic essay about: {topic}. Thesis: {thesis}. Words: {word_count}. Style: {style}. Language: {language}.', fields: JSON.stringify([{name:'topic',label:'Essay Topic',type:'text',required:true},{name:'thesis',label:'Thesis Statement',type:'text',required:true},{name:'word_count',label:'Word Count',type:'number',required:false},{name:'style',label:'Citation Style',type:'text',required:false}]), isPremium: 1, isFeatured: 0, sortOrder: 26 },
  { id: 't-27', name: 'Grammar Checker', slug: 'grammar-checker', description: 'Fix grammar and improve writing', icon: 'CheckCircle', categoryId: 'cat-10', prompt: 'Check and fix grammar in this text. Explain corrections: {content}. Language: {language}.', fields: JSON.stringify([{name:'content',label:'Text to Check',type:'textarea',required:true}]), isPremium: 0, isFeatured: 0, sortOrder: 27 },
  { id: 't-28', name: 'Video Scripts', slug: 'video-scripts', description: 'Write engaging video scripts', icon: 'Video', categoryId: 'cat-11', prompt: 'Write a video script about: {topic}. Duration: {duration}. Platform: {platform}. Style: {style}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'topic',label:'Video Topic',type:'text',required:true},{name:'duration',label:'Duration',type:'text',required:false},{name:'platform',label:'Platform',type:'text',required:false},{name:'style',label:'Style',type:'text',required:false}]), isPremium: 0, isFeatured: 1, sortOrder: 28 },
  { id: 't-29', name: 'YouTube Tags', slug: 'youtube-tags', description: 'Generate YouTube tags for SEO', icon: 'Hash', categoryId: 'cat-11', prompt: 'Generate {count} YouTube tags for video: {video_title}. Topic: {topic}. Language: {language}.', fields: JSON.stringify([{name:'video_title',label:'Video Title',type:'text',required:true},{name:'topic',label:'Topic',type:'text',required:false},{name:'count',label:'Number of Tags',type:'number',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 29 },
  { id: 't-30', name: 'Tone Changer', slug: 'tone-changer', description: 'Change the tone of any text', icon: 'Wand2', categoryId: 'cat-12', prompt: 'Rewrite this text in a {target_tone} tone: {content}. Language: {language}.', fields: JSON.stringify([{name:'content',label:'Text',type:'textarea',required:true},{name:'target_tone',label:'Target Tone',type:'text',required:true}]), isPremium: 0, isFeatured: 0, sortOrder: 30 },
  { id: 't-31', name: 'Text Extender', slug: 'text-extender', description: 'Expand short text into longer content', icon: 'Maximize2', categoryId: 'cat-12', prompt: 'Expand this text to approximately {word_count} words while keeping the meaning: {content}. Tone: {tone}. Language: {language}.', fields: JSON.stringify([{name:'content',label:'Text to Expand',type:'textarea',required:true},{name:'word_count',label:'Target Words',type:'number',required:false}]), isPremium: 0, isFeatured: 0, sortOrder: 31 },
]

async function main() {
  console.log('🌱 Seeding templates to Turso...\n')

  // Seed categories
  console.log('📂 Categories:')
  for (const cat of categories) {
    await client.execute({
      sql: `INSERT OR IGNORE INTO template_categories (id, name, slug, icon, description, sortOrder, isActive) VALUES (?, ?, ?, ?, ?, ?, 1)`,
      args: [cat.id, cat.name, cat.slug, cat.icon, cat.description, cat.sortOrder],
    })
    console.log(`  ✓ ${cat.name}`)
  }

  // Seed templates
  console.log('\n📝 Templates:')
  for (const t of templates) {
    await client.execute({
      sql: `INSERT OR IGNORE INTO templates (id, name, slug, description, icon, categoryId, prompt, fields, outputType, toneOptions, languageOptions, isPremium, isFeatured, sortOrder, isActive) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'markdown', ?, ?, ?, ?, ?, 1)`,
      args: [t.id, t.name, t.slug, t.description, t.icon, t.categoryId, t.prompt, t.fields, toneOpts, langOpts, t.isPremium, t.isFeatured, t.sortOrder],
    })
    console.log(`  ✓ ${t.name}`)
  }

  // Verify
  const catCount = await client.execute('SELECT COUNT(*) as cnt FROM template_categories')
  const tmpCount = await client.execute('SELECT COUNT(*) as cnt FROM templates')
  console.log(`\n✅ Done! Categories: ${catCount.rows[0].cnt}, Templates: ${tmpCount.rows[0].cnt}`)
}

main().catch(console.error)
